[tool.poetry]
name = "bitsea"
version = "0.1.0"
description = ""
authors = ["OGS"]
readme = "README.md"
packages = [
    { include = "bitsea", from="src" },
]

[tool.poetry.dependencies]
python = "^3.9"
numpy = ">1.26.2"
scipy = "^1.12.0"
netcdf4 = "^1.6.5"

scikit-learn = { version = "^1.4.2", optional = true }
matplotlib = { version = ">3.7.5", optional = true }
cartopy = { version = "^0.23.0", optional = true }
geopy = { version = "^1.4.0", optional = true }

[tool.poetry.extras]
ml = ["scikit-learn"]
viz = ["matplotlib"]
cartography = ["cartopy", "geopy"]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pre-commit = "^3.8.0"
requests = "^2.32.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
markers = [
    "uses_test_data: Needs external data not downloaded from the repository"
]
