#! /bin/bash

#SBATCH --job-name=SUPERF_ppcon
#SBATCH --ntasks=1
#SBATCH --time=01:05:00
#SBATCH --account=OGS23_PRACE_IT
#SBATCH --partition=g100_usr_interactive
#SBATCH --gres=gpu:1
#SBATCH --mail-type=ALL
#SBATCH --mail-user=camadio@inogs.it

INDIR="/g100_scratch/userexternal/camadio0/PPCON/CODE_loss_attention_max_PPCon/"

/$INDIR/Launcher_ca.sh

date

